const bios = [
  {
    name: "Tasha R. Inniss",
    imgSrc: "/team/tasha_inniss.png",
    story: "Tasha R. Inniss, Ph.D., is the Associate Provost for Research at Spelman College. In this role, she serves as the chief advocate for research at the College and leads the Office of Research, Innovation, and Collaboration (ORIC). Dr. Inniss provides leadership and strategic direction for all activities related to individual or interdisciplinary research, creative pursuits, collaborative partnerships, and programmatic initiatives for undergraduate research. Dr. Inniss also holds a tenured faculty appointment in the Department of Mathematics."
    + "<br><br> Prior to returning to Spelman, Inniss was the inaugural director of education and industry outreach at INFORMS, the world’s largest professional society for professionals in the fields of operations research, management science and analytics. She also did a rotation at the National Science Foundation in the Directorate of Education and Human Resources where she served as the acting deputy division director of the Division of Human Resource Development and before that, as the co-lead of the Louis Stokes Alliances for Minority Participation (LSAMP) Program."
    + "<br><br> Originally from New Orleans, Dr. Inniss graduated summa cum laude from Xavier University of Louisiana with a Bachelor of Science degree in mathematics. She earned a Master of Science degree in applied mathematics from the Georgia Institute of Technology and a doctorate in applied mathematics from the University of Maryland, College Park. Her first faculty position after completing her doctorate was as a Clare Boothe Luce Professor of Mathematics at Trinity College (now Trinity Washington University) in Washington, D.C. She began as a mathematics faculty member at Spelman College in January 2004."
    + "<br><br>As an applied mathematician, her research interests are in the areas of operations research, applied statistics and data science/data mining. In addition to Dr. Inniss' research interests, she also has a passion for teaching mathematics and encouraging undergraduate students to pursue degrees in STEM disciplines. When she was a junior faculty member at Spelman College, Inniss received a Presidential Award for Excellence in Teaching because of her innovative teaching techniques and dedication to helping students to see how mathematics is applied in the real-world."
    + "<br><br> Dr. Inniss serves as the principal investigator of Spelman’s Center of Excellence for Minority Women in STEM. She is also a member of the National Academies of Sciences, Engineering and Medicine’s (NASEM’s) Board on Higher Education and Workforce as well as an Executive Council Member for the Roundtable on Systemic Change in Undergraduate STEM Education. ",
  },
  {
    name: "Leyte Winfield",
    imgSrc: "/team/leyte_winfield.png",
    story: "Leyte L. Winfield is a full professor of chemistry and biochemistry at Spelman College where she serves as Division Chair for the Natural Sciences and Mathematics. Her leadership experience extends across and beyond the academic environment. As chair of the Department of Chemistry and Biochemistry at Spelman College, Winfield led the department’s efforts to broaden the curriculum to meet the ideals of a liberal arts education while simultaneously providing students with resources that promote improved engagement and performance in the majors. In addition to her role as department chair, her record of leadership has included service as interim associate provost of research, as well as directorships for programmatic efforts geared toward improving diversity in STEM." +
    + "<br><br>A medicinal chemist, she has designed and synthesized compounds intended to address problems posed by existing cancer therapies. She has received six patents for compositions of mater covering more than 800 unique structural entities. Complementing her lab-based success, Dr. Winfield is leading NSF funds research related to the participation and success of underrepresented groups in STEM. Specifically, her work deals with characterizing how students of color demonstrate agency in the pursuit of STEM careers and the ecosystems that nurture such agency. For these collaborative efforts, she has received more than $6.9 million. Dr. Winfield is chairing the internal steering committee for the newly established Center of Excellence for Women of Color in STEM at Spelman College. Funded by the Department of Defense, the Center builds upon Spelman’s legacy of preparing women of African descent to excel in STEM careers. She is the lead editor of a book through ACS Publications entitled, Growing Diverse STEM Communities: Methodology, Impact, and Evidence. Dr. Winfield is a coach and facilitator for the AAC&U PKAL STEM Leadership Institute and holds a post-graduate certificate in academic leadership from the Chicago School of Clinical Psychology. In addition, she chairs the Minority Chemist Subdivision of the ACS Division of Professional Relations, is a member of the ACS Committee on Professional Training, serves on the Editorial Advisory Board for the Journal of Chemical Education, and is a member of the leadership board OrganicERs, a learning community for the development and dissemination of organic chemistry pedagogies and learning resources.",
  },
  {
    name: "Tinaz Pavri",
    imgSrc: "/team/tinaz_pavri.png",
    story: "Tinaz Pavri is Division Chair for Social Sciences and Education at Spelman College and Founding Director of the Asian Studies Program.  She is a professor of Political Science. Her Ph.D. in Political Science/International Relations is from The Ohio State University." +
    "<br><br> Dr. Pavri has taught a range of Political Science courses including Comparative Political Systems and Introduction to Asian Studies. Her research and publication interests lie in the area of security studies and conflict resolution, national identity and globalization. Her geographic area of expertise is South Asia. She has published numerous articles, book chapters and a co-edited book on these and other topics. " +
    "<br><br> Dr. Pavri has served as President of the Georgia Political Science Association (GPSA). She has obtained grants from the Japan Foundation, U.S. Army War College, Southern Educational Foundation (SEF), United Negro College Fund (UNCF and UNCFSP). She directed Spelman’s $1.2m grant, the Career Pathways Initiative. Through her work, she has consistently elevated the role of black women and other minorities. In 2015, she received the Donald T. Wells award for outstanding service to the Georgia Political Science Association. She was awarded the college’s Presidential award for scholarship in 2009 and the Presidential award for service in 2022."
  },
  {
    name: "Brandi Taylor",
    imgSrc: "/team/brandi_taylor.png",
    story: "Brandi Taylor is a proud Spelman College Alumna with a Bachelor of Science in Chemistry and a Graduate Certificate in Clinical Health Informatics from Georgia State University.    Brainstorming sessions and mind mapping are the name of the game for Brandi.  She is a self-described creative that is passionate about supporting students through various avenues of skill development and relationship building." + 
    "<br><br> Brandi has 17-plus years of demonstrated passion for supporting undergraduate students as a staff member at Spelman College.  She has helped lead programmatic development efforts with the NIH RISE program and currently serves as the Undergraduate Research & Training Programs Manager (URTP) since its inception in 2019.   During her time as URTP Manager Brandi has led efforts to foster undergraduate research across campus in areas such as Research Day, ORICeLearn, URTP Engagers peer coaching, and a host of trainings & workshops." +
    "<br><br> When she’s not at Spelman, Brandi loves spending time with her family and “playing in the dirt”.  Brandi finds peace and solace in seeing her flowers and vegetables grow.  It’s one of those beautiful parts of life that give birth to science and art. "
  },
  {
    name: "Miesha Williams",
    imgSrc: "/team/miesha_williams.png",
    story: "Dr. Miesha Williams is Vice Chair and Associate Professor in the Spelman College Economics Department. She researches macroeconomic policies in Africa, in the U.S., and disparate outcomes impacting race. During 2021- 2022 she was a Visiting Scholar with USC Price School of Public Policy.  Currently she is conducting research on cognitive decline across races as a USC RCMAR Scholar.  She’s obtained sponsorship from Title III, NSF, USDA, Carnegie Foundation, Koch Foundation and NIH.  She’s published in AEA Papers and Proceedings, Southern Economic Journal, Journal of Economics Race and Policy, Review of Black Political Economy, and co-edited a special issue on Social Justice with the Agricultural and Resource Economics Review.  She is a National Economic Association Board Member, Editorial Board Member with Journal of Business and Economic Studies, secretary for African Political Economic Association, and Research Associate with UNO Entrepreneurship Center. Williams’ Economics’ B.S. (2007) is from FAMU, while her M.A. (2010) and Ph.D. (2014) is from University of Alabama.",
  },
  {
    name: "Courtney Powell",
    imgSrc: "/team/courtney_powell.png",
    story: "As a graduate of North Carolina A&T State University, Courtney Powell brings a wealth of knowledge and expertise to the world of digital development. With a focus on web development and software implementation, Courtney excels in turning complex challenges into elegant solutions." +
    "<br><br> Courtney's journey in the world of technology is fueled by a deep-rooted passion for problem solving. The ability to dissect intricate issues and design effective solutions has been a hallmark of her career." +
    "<br><br> Beyond the digital realm, Courtney finds inspiration through the lens of a camera. Photography serves as both a creative outlet and a means of capturing the beauty of diverse landscapes during travels. This harmonious blend of technical prowess and artistic expression defines Courtney's approach to life." +
    "<br><br> \"I am because we are\" is more than a phrase for Courtney—it's a guiding principle. Embracing interconnectedness and community, Courtney believes that individual growth is intertwined with collective progress. This philosophy fuels her dedication to collaboration and innovation.",
  },
  {
    name: "Tiffany Oliver",
    imgSrc: "/team/",
    story: "Dr. Tiffany Oliver is a dynamic motivational speaker, author, professor, and scientist. For almost 20 years, she has captivated audiences with her research and presentations on leadership, persistence, and excellence. A native of Detroit, Michigan, Tiffany is celebrated for her TedxTalk -  Creating diverse and equitable initiatives in data science. She serves an Associate Professor and Chair of the Biology Department at Spelman College where she is a Carnegie and Rockefeller Distinguished Research Scholar. Dr. Oliver received her Ph.D. in Genetics and Molecular Biology from Emory University; her research uses both molecular and data-science based approaches to characterize genes and mutations that play a role in disease." +
    "<br><br> Dr. Oliver is passionate about increasing diversity in STEM (science, technology, engineering, and mathematics) disciplines. She does this by running a research lab that employs and engages students in scientific research." +
    "<br><br> However, Dr. Oliver also creates opportunities for cross-disciplinary collaboration and experiential learning by leading projects that integrate STEM and the arts, better known as STEAM. Studies show that STEAM projects promote inquiry, problem solving, dialogue, critical thinking, and experiential learning.  Her students have won cash prizes and scholarships for their participation in activities including but not limited to the Army Research Lab’s Student Design Competition, where they created a fully functional, Unmanned Aerial Vehicle (UAV), otherwise known as a “drone”, upon being provided with nothing but a sample of the bacteriaDr. Oliver also worked with an interdisciplinary team of faculty and students that placed second in the International Bio Design Competition (BDC). In her first year of participation, her students placed second out of 51 international institutions for the design of a bio-inspired garment, that imbued modular biosensors and spider silk to provide physical protection as well as enable the communication of health and emotions between wearers via a virtual network." +
    "<br><br> Dr. Oliver’s passion for increasing diversity, specifically within the field of data science is highlighted by the student and faculty research programs she has created. She currently directs three undergraduate research programs that teach students how to code and provides them with the research experience, networking, and professional development needed to be competitive for careers in the field of data science. These programs have been funded by Fortune 500 companies including the Southern Company and Accenture. Dr. Oliver also serve as the Co-PI on a grant from the National Science Foundation (NSF), which funds a 3+2 master’s  program that allows STEM majors to receive both their Bachelor’s and a Master’s degree in Data Science in only 5 years. As it pertains to opportunities for faculty, Dr. Oliver a serves as a team lead and co-facilitator for the United Negro College Fund (UNCF) and Excelencia’s “Leveraging Big Data to Achieve Equity” program. In this capacity, she teaches faculty how to code and about the importance of data integrity, privacy and confidentiality. Dr. Oliver presents nationally and internationally to student groups, major scientific societies, faculty, and other interest groups. "
  },
  {
    name: "Holly Smith",
    imgSrc: "/team/",
    story: "Holly A. Smith is the College Archivist at Spelman College. She received her B.A. in History and Black Studies from The College of William and Mary, an M.A. in History from Yale University, and an M.S. in Library and Information Science from Simmons College. She co-authored the article “This [Black] Woman’s Work: Exploring Archival Projects that Embrace the Identity of the Memory Worker” (KULA Journal, 2018:2), and authored the pieces “Radical Love: Documenting Underrepresented Communities Using Principles of Radical Empathy” (Journal for the Society of North Carolina Archivists, 2018: 15) and “Wholeness is No Trifling Matter: Black Feminist Archival Practice and The Spelman College Archives” (The Black Scholar 52:2).  She is passionate about community archives and archival advocacy related to collections for historically under documented communities.  " 
  },
  {
    name: "Valeisha Ellis",
    imgSrc: "/team/",
    story: "Dr. Valeisha Ellis is an assistant professor in the Education Department at Spelman College.  She has experience in S.T.E.A.M. curriculum and instruction, reading, special education and teacher education.  Dr. Ellis’ research interests include STEM identity development, effective models of establishing and maintaining P-12 S.T.E.A.M. school and community partnerships, effective pre-service STEM field and clinical models for teacher education, and multidisciplinary education research.  In 2023, Dr. Ellis was awarded a grant from Google Education. Her project focuses on innovative solutions to our K-12 STEM community, addressing the current challenges of Computer Science (CS) workforce diversity, lack of CS career exposure for educators and K-12 students, and heightening CS engagement. She is the program chair of the Research Focus on Black Education Special Interest Group (SIG) at the American Association of Education Research Association (AERA). She is a member of the Atlanta University Center (AUC) K-12 Data Science Initiative and the steering committee for Spelman College’s Center of Excellence for Minority Women in STEM. Her most recent publications include “The perspectives and pedagogies of middle school social justice educators.”, “Changing the Face of STEM: Review of Literature on The Role of Mentors in the Success of Undergraduate Black Women in STEM Education.”, and “An HBCU Initiative to Build Effective Partnerships for Pre-Service Teachers’ Field and Clinical Experiences.”     "
  },
  {
    name: "Sierra Griffith",
    imgSrc: "/team/",
    story: "Sierra Griffith is a sophomore at Spelman College. She is pursuing a degree in Economics (BA) but has a focus on marketing. Sierra hopes to learn more about different industries' strategies to interest their target audience. Such industries can include fashion, media, technology, or news agencies. Her interest in marketing stems from her passion for media and the creative plans one uses to convince an audience about a film. Ms. Griffith also recently took a course learning how people use technology to influence consumers positively and negatively. Entering her second year of college, Sierra hopes to gain more experience with various companies and progress toward her career. "
  },
  {
    name: "Kailen Bain",
    imgSrc: "/team/",
    story: "Kailen Bain is a sophomore Chemistry major on the pre-dental track at Spelman College. She is 1 of 5 students selected to be in the first cohort of Ralph Lauren Corporate Foundation Scholars and she is also a member of the Ethel Waddell Githii Honors Program. Throughout her time in school, she has been devoted to helping children within the metro-Atlanta community explore their passions in S.T.E.M. Over the past year, she has worked with nonprofit organizations that focus on providing access to S.T.E.M resources in low-income communities. In her free time, she enjoys creating cosmetic products for her business Kay Nichole Beauty, which she founded in 2019. With experience in clinical job shadowing, entrepreneurship, and volunteering she is eager to gain more exposure through professional work experiences. "
  },
  {
    name: "Shanina Sanders Johnson",
    imgSrc: "/team/",
    story: "Dr. Shanina Sanders Johnson is an Associate Professor in the Department of Chemistry and Biochemistry at Spelman College. Her teaching and scholarly activities align with her goals of nurturing the next generation of Black women in STEM and creating a more inclusive field. She introduced culturally relevant teaching into the organic lectures and labs at Spelman to engage students and promote science identity among Black women. Dr. Sanders has received funding from the Associated Colleges of the South and the National Science Foundation to support teaching and research activities in this area. She has organized workshops, presented related work at conferences, academic institutions, and published journal articles and editorials that highlight efforts to engage diverse audiences in STEM and make STEM curriculum more inclusive. As a teacher scholar, she has an active synthetic chemistry research lab where she trains students interested in STEM careers or graduate school in chemistry."
  },
  {
    name: "Na’Taki Osborne Jelks",
    imgSrc: "/team/",
    story: "Dr. Na’Taki Osborne Jelks is an Assistant Professor in the Environmental and Health Sciences Program at Spelman College in Atlanta, GA.  Dr. Jelks investigates urban environmental health disparities; the role that place, race, and social factors play in influencing health; cumulative environmental risks and health; the impact of climate change on vulnerable populations, and the connection between urban watersheds, pollution, the built environment, and health.  She also develops, implements, and evaluates community-based initiatives that set conditions to enable low-income and communities of color to empower themselves to reduce exposure to environmental health hazards and improve health and quality of life. Jelks is particularly interested in approaches that engage environmentally overburdened communities in monitoring local environmental conditions, generating actionable data for community change, and developing effective community-based interventions that revitalize toxic, degraded spaces into healthy places. She is currently co-leading UrbanHeatATL, a research initiative in which Atlanta-based students and community members are mapping urban heat islands in Atlanta with community science. Her research and public health practice are supported by private and public agencies and foundations such as the U.S. Environmental Protection Agency, the National Institute of Environmental Health Sciences, and The Rockefeller, Robert Wood Johnson and National Science Foundations. " +
    "<br><br> Dr. Jelks co-founded the West Atlanta Watershed Alliance (WAWA), a community-based environmental justice organization that works to grow a cleaner, greener, healthier, more sustainable West Atlanta through authentic community engagement, organizing, education, community science, and participatory research. Since 2018 she has served on the National Environmental Justice Advisory Council (NEJAC), a federal advisory committee that works to integrate environmental justice into the Environmental Protection Agency’s programs, policies and activities as well as to improve the environment or public health in communities disproportionately burdened by environmental harms and risks. Jelks is currently one of two co- chairs of the NEJAC. A nationally recognized leader in engaging urban communities and youth of color in environmental stewardship, Jelks also co-founded the National Wildlife Federation’s Atlanta Earth Tomorrow Program, a youth environmental leadership and environmental justice program, in 2001 and served as the program director from 2005 until 2017. " +
    "<br><br> Jelks studied Chemistry and Civil and Environmental Engineering at Spelman College and the Georgia Institute of Technology respectively before earning a Master of Environmental and Occupational Health degree at Emory University and a Ph.D. in Public Health at Georgia State University." +
    "<br><br> In 2021, Dr. Jelks was named an Ecological Society of America Excellence in Ecology Scholar and was selected as one of six national winners of Rachel’s Network Catalyst Award for women of color environmental leaders.  In 2022, Dr. Jelks was selected as a Harvard University/JBP Foundation Environmental Health Scholar."
  },
  {
    name: "Elethia Tillman",
    imgSrc: "/team/",
    story: "Dr. Elethia Tillman is currently a Senior Lecturer and Co-Chair of Spelman’s biology department. She has a Ph.D. in biomedical science with emphasis in the molecular and cellular pathways that lead to cardiovascular disease from Meharry Medical College. Dr. Tillman’s broad interests include medical communication, health disparities and women’s health and she is passionate about enhancing participation among minority women in STEM. Dr. Tillman is also a freelance medical writer, providing science communication support across multiple therapeutic areas in clinical research and continuing medical education initiatives. Her Biology of Women course empowers high school and undergraduate minority women to have agency over their healthcare experiences through exploration of their unique biology and how biology influences their lived experiences and she has also mentored students in data science research examining maternal health disparities. As a member of the Atlanta University Center cohort of the UNCF/Excelencia data science program, Dr. Tillman and her colleagues presented data that identified race and sex as predictors of STEM PhD students taking gap years which extends the time to degree completion and entry into a STEM profession. "
  },
  {
    name: "Celeste Lee",
    imgSrc: "/team/",
    story: "Dr. Celeste Lee is an assistant professor of Sociology at Spelman College; she teaches courses on multivariate analysis, sociology of race and racism, research methods, and the sociology of health. She also serves as director of Spelman’s Census Information Center and a member of steering committee for the Center of Excellence for Minority Women in STEM. " +
    "<br><br> Dr. Lee’s areas of expertise include racial and ethnic inequality, ideology, sociology of health, education, and quantitative methods. Ultimately, her research agenda aims to interrogate how race and ethnicity impact people’s lived experiences, the relationship between racialized experiences and racial ideology, and groups’ understanding of broader racial dynamics. In 2023, Dr. Lee was awarded a health equity grant from the Thurgood Marshall College Fund and Novartis Alliance. Her project focuses on nursing interventions for obstetric emergencies as a pathway for addressing high maternal mortality rates. She also serves as Co-PI on a grant from the National Science Foundation; the grant supports research on Black women’s experiences in computer science.  In the fall 2021-2022 academic year, she received a UNCF/ Mellon Faculty in Residency Grant and spent the spring semester as a fellow at the James Weldon Johnson Institute for the Study of Race and Difference. During her residency, Dr. Lee completed her most recent publication, \"Beyond the Four Frames of Colorblind Ideology: The Impact of Colorblind Ideology on Black Millennial's Racial Views\"; ublished Summer 2022 in “Phylon.” " +
    "<br><br> Dr. Lee is a proud Atlanta native. She earned her doctoral and bachelor’s degrees in Sociology from Emory University. She also holds a master’s in education from Duke University. "
  },
  {
    name: "Marilyn A. Davis",
    imgSrc: "/team/",
    story: "Associate Professor of Political Science, Spelman College" +
    "<br><br> Goals and Aspirations:  To teach, encourage, advise, mentor, and nurture undergraduate students throughout their matriculation." +
    "<br><br>Achievements " +
    "<ul>The American Political Science Association, Best Syllabi Recognition, 1980s. Political Science 497, Senior Seminar; Political Science 415, Ancient and Classical Political Theory/Political Science 417, Political Theory from Machiavelli to the Present; and Political Science 419, The American Presidency.</ul>" +
    "<ul>Sears-Roebuck Foundation Teaching Excellence and Campus Leadership Award, April 1990.</ul>" +
    "<ul>Spelman College Provost’s Award for Excellence in Academic Advising, August 2019.</ul>" + 
    "<ul>Several published articles and book chapters on the voting behavior of African Americans and the national electoral success of African American Women, 1980s through 2020s.</ul>" +
    "<ul>Published and widely cited nationally, a political science research article with Spelman College faculty colleagues, PS, a publication of the American Political Science Association, 2022.</ul>" +
    "<ul>Core II, Center for Excellence, Black Women in STEM, Spelman College, 2023.</ul>"
  },
]

export default bios