const bios = [
  {
    name: "Tasha R. Inniss, Ph.D",
    imgSrc: "/team/tasha_inniss.png",
    story: "Tasha R. Inniss, Ph.D., is the Associate Provost for Research at Spelman College. In this role, she serves as the chief advocate for research at the College and leads the Office of Research, Innovation, and Collaboration (ORIC). Dr. Inniss provides leadership and strategic direction for all activities related to individual or interdisciplinary research, creative pursuits, collaborative partnerships, and programmatic initiatives for undergraduate research. Dr. Inniss also holds a tenured faculty appointment in the Department of Mathematics."
    + "<br><br> Prior to returning to Spelman, Inniss was the inaugural director of education and industry outreach at INFORMS, the world’s largest professional society for professionals in the fields of operations research, management science and analytics. She also did a rotation at the National Science Foundation in the Directorate of Education and Human Resources where she served as the acting deputy division director of the Division of Human Resource Development and before that, as the co-lead of the Louis Stokes Alliances for Minority Participation (LSAMP) Program."
    + "<br><br> Originally from New Orleans, Dr. Inniss graduated summa cum laude from Xavier University of Louisiana with a Bachelor of Science degree in mathematics. She earned a Master of Science degree in applied mathematics from the Georgia Institute of Technology and a doctorate in applied mathematics from the University of Maryland, College Park. Her first faculty position after completing her doctorate was as a Clare Boothe Luce Professor of Mathematics at Trinity College (now Trinity Washington University) in Washington, D.C. She began as a mathematics faculty member at Spelman College in January 2004."
    + "<br><br>As an applied mathematician, her research interests are in the areas of operations research, applied statistics and data science/data mining. In addition to Dr. Inniss' research interests, she also has a passion for teaching mathematics and encouraging undergraduate students to pursue degrees in STEM disciplines. When she was a junior faculty member at Spelman College, Inniss received a Presidential Award for Excellence in Teaching because of her innovative teaching techniques and dedication to helping students to see how mathematics is applied in the real-world."
    + "<br><br> Dr. Inniss serves as the principal investigator of Spelman’s Center of Excellence for Minority Women in STEM. She is also a member of the National Academies of Sciences, Engineering and Medicine’s (NASEM’s) Board on Higher Education and Workforce as well as an Executive Council Member for the Roundtable on Systemic Change in Undergraduate STEM Education. ",
  },
  {
    name: "Leyte Winfield",
    imgSrc: "/team/leyte_winfield.png",
    story: "Leyte L. Winfield is a full professor of chemistry and biochemistry at Spelman College where she serves as Division Chair for the Natural Sciences and Mathematics. Her leadership experience extends across and beyond the academic environment. As chair of the Department of Chemistry and Biochemistry at Spelman College, Winfield led the department’s efforts to broaden the curriculum to meet the ideals of a liberal arts education while simultaneously providing students with resources that promote improved engagement and performance in the majors. In addition to her role as department chair, her record of leadership has included service as interim associate provost of research, as well as directorships for programmatic efforts geared toward improving diversity in STEM." +
    + "<br><br>A medicinal chemist, she has designed and synthesized compounds intended to address problems posed by existing cancer therapies. She has received six patents for compositions of mater covering more than 800 unique structural entities. Complementing her lab-based success, Dr. Winfield is leading NSF funds research related to the participation and success of underrepresented groups in STEM. Specifically, her work deals with characterizing how students of color demonstrate agency in the pursuit of STEM careers and the ecosystems that nurture such agency. For these collaborative efforts, she has received more than $6.9 million. Dr. Winfield is chairing the internal steering committee for the newly established Center of Excellence for Women of Color in STEM at Spelman College. Funded by the Department of Defense, the Center builds upon Spelman’s legacy of preparing women of African descent to excel in STEM careers. She is the lead editor of a book through ACS Publications entitled, Growing Diverse STEM Communities: Methodology, Impact, and Evidence. Dr. Winfield is a coach and facilitator for the AAC&U PKAL STEM Leadership Institute and holds a post-graduate certificate in academic leadership from the Chicago School of Clinical Psychology. In addition, she chairs the Minority Chemist Subdivision of the ACS Division of Professional Relations, is a member of the ACS Committee on Professional Training, serves on the Editorial Advisory Board for the Journal of Chemical Education, and is a member of the leadership board OrganicERs, a learning community for the development and dissemination of organic chemistry pedagogies and learning resources.",
  },
  {
    name: "Tinaz Pavri",
    imgSrc: "/team/tinaz_pavri.png",
    story: "Tinaz Pavri is Division Chair for Social Sciences and Education at Spelman College and Founding Director of the Asian Studies Program.  She is a professor of Political Science. Her Ph.D. in Political Science/International Relations is from The Ohio State University." +
    "<br><br> Dr. Pavri has taught a range of Political Science courses including Comparative Political Systems and Introduction to Asian Studies. Her research and publication interests lie in the area of security studies and conflict resolution, national identity and globalization. Her geographic area of expertise is South Asia. She has published numerous articles, book chapters and a co-edited book on these and other topics. " +
    "<br><br> Dr. Pavri has served as President of the Georgia Political Science Association (GPSA). She has obtained grants from the Japan Foundation, U.S. Army War College, Southern Educational Foundation (SEF), United Negro College Fund (UNCF and UNCFSP). She directed Spelman’s $1.2m grant, the Career Pathways Initiative. Through her work, she has consistently elevated the role of black women and other minorities. In 2015, she received the Donald T. Wells award for outstanding service to the Georgia Political Science Association. She was awarded the college’s Presidential award for scholarship in 2009 and the Presidential award for service in 2022."
  },
  {
    name: "Brandi Taylor",
    imgSrc: "/team/brandi_taylor.png",
    story: "Brandi Taylor is a proud Spelman College Alumna with a Bachelor of Science in Chemistry and a Graduate Certificate in Clinical Health Informatics from Georgia State University.    Brainstorming sessions and mind mapping are the name of the game for Brandi.  She is a self-described creative that is passionate about supporting students through various avenues of skill development and relationship building." + 
    "<br><br> Brandi has 17-plus years of demonstrated passion for supporting undergraduate students as a staff member at Spelman College.  She has helped lead programmatic development efforts with the NIH RISE program and currently serves as the Undergraduate Research & Training Programs Manager (URTP) since its inception in 2019.   During her time as URTP Manager Brandi has led efforts to foster undergraduate research across campus in areas such as Research Day, ORICeLearn, URTP Engagers peer coaching, and a host of trainings & workshops." +
    "<br><br> When she’s not at Spelman, Brandi loves spending time with her family and “playing in the dirt”.  Brandi finds peace and solace in seeing her flowers and vegetables grow.  It’s one of those beautiful parts of life that give birth to science and art. "
  },
  {
    name: "Miesha Williams",
    imgSrc: "/team/miesha_williams.png",
    story: "Dr. Miesha Williams is Vice Chair and Associate Professor in the Spelman College Economics Department. She researches macroeconomic policies in Africa, in the U.S., and disparate outcomes impacting race. During 2021- 2022 she was a Visiting Scholar with USC Price School of Public Policy.  Currently she is conducting research on cognitive decline across races as a USC RCMAR Scholar.  She’s obtained sponsorship from Title III, NSF, USDA, Carnegie Foundation, Koch Foundation and NIH.  She’s published in AEA Papers and Proceedings, Southern Economic Journal, Journal of Economics Race and Policy, Review of Black Political Economy, and co-edited a special issue on Social Justice with the Agricultural and Resource Economics Review.  She is a National Economic Association Board Member, Editorial Board Member with Journal of Business and Economic Studies, secretary for African Political Economic Association, and Research Associate with UNO Entrepreneurship Center. Williams’ Economics’ B.S. (2007) is from FAMU, while her M.A. (2010) and Ph.D. (2014) is from University of Alabama.",
  },
  {
    name: "Courtney Powell",
    imgSrc: "/team/courtney_powell.png",
    story: "As a graduate of North Carolina A&T State University, Courtney Powell brings a wealth of knowledge and expertise to the world of digital development. With a focus on web development and software implementation, Courtney excels in turning complex challenges into elegant solutions." +
    "<br><br> Courtney's journey in the world of technology is fueled by a deep-rooted passion for problem solving. The ability to dissect intricate issues and design effective solutions has been a hallmark of her career." +
    "<br><br> Beyond the digital realm, Courtney finds inspiration through the lens of a camera. Photography serves as both a creative outlet and a means of capturing the beauty of diverse landscapes during travels. This harmonious blend of technical prowess and artistic expression defines Courtney's approach to life." +
    "<br><br> \"I am because we are\" is more than a phrase for Courtney—it's a guiding principle. Embracing interconnectedness and community, Courtney believes that individual growth is intertwined with collective progress. This philosophy fuels her dedication to collaboration and innovation.",
  },
]

export default bios