# Start with node image found at hub.docker.com/_/node
FROM node
# Set working directory to /app, this is within the custom image
WORKDIR /app
# Copy package.json into the current directory "." (/app) 
COPY package.json . 
# Run npm install to install all dependencies
RUN npm install
# Copy the rest of files into the container
COPY . .
ENV REACT_APP_NAME=myName
# Expose port that app is listening on
EXPOSE 3000
# Start dev server
CMD ["npm", "start"]