name: Enforce Merges to `latest`

on:
  pull_request:
    branches:
      - latest

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'latest' && github.head_ref != 'main'
        run: |
          echo "ERROR: You can only merge to latest from main."
          exit 1