name: "MkDocs Deploy"
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Generate Cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - name: Set up Cache
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: mkdocs gh-deploy --force
